### ISSUE TITLE
Feature Request:  Plain text output option

### ISSUE THREAD

**Issue by khaytsus** [The-Kid-Gid/nextinspace#3]
The panes are neat, but it would be nice to have a plain text output mode that just outputs text, no panes, no colors.

**Comment by The-Kid-Gid** [comment]
Do you mean something machine readable? Or is this for some other purpose?

**Comment by khaytsus** [comment]
To make it easier to copy paste to someone, to perhaps output from an irc client script, things like that.  Not so much machine readable, that'd be csv, xml, json, etc ;)

**Comment by The-Kid-Gid** [comment]
Sounds interesting, definitely something I'll consider doing. Removing colors would be easy, and the information could be printed without box drawing characters and indents, with blank lines in between items.

**Comment by The-Kid-Gid** [comment]
Hey @khaytsus, I have some interest in projects where nextinspace might be used as a backend, and because of the nature of the data it provides (structured), I'm thinking of adding a JSON output flag. Would this be of any interest to you? It could be parsed with something like [`jq`](https://github.com/stedolan/jq).

**Comment by khaytsus** [comment]
@The-Kid-Gid I dig json, and use jq a lot in scripting seems fine with me for a format output type.  :+1:

**Comment by The-Kid-Gid** [comment]
OK, I think we'll move forward with JSON output.

**Comment by The-Kid-Gid** [comment]
Closed with 3f5360a6c4a90af4d7e8f2eb6a5fcd354c2f3a61
